import { BarrierTypeModel } from "../../domain/models/BarrierTypeModel";
import { Prisma,BarrierType } from "@prisma/client";
import { BarrierTypeCreateDto, BarrierTypeUpdateDto } from "../dto/barrierType.dto";

export class BarrierTypeMapper {
  static fromCreateDtoToModel(dto: BarrierTypeCreateDto): BarrierTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: BarrierTypeUpdateDto): BarrierTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: BarrierTypeModel): Prisma.BarrierTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}