import { CategoryOfHighwaysModel } from "../../domain/models/CategoryOfHighwaysModel";
import { Prisma,CategoryOfHighways } from "@prisma/client";
import { CategoryOfHighwaysCreateDto, CategoryOfHighwaysUpdateDto } from "../dto/categoryOfHighways.dto";

export class CategoryOfHighwaysMapper {
  static fromCreateDtoToModel(dto: CategoryOfHighwaysCreateDto): CategoryOfHighwaysModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: CategoryOfHighwaysUpdateDto): CategoryOfHighwaysModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: CategoryOfHighwaysModel): Prisma.CategoryOfHighwaysCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}