import { CoverageTypeModel } from "../../domain/models/CoverageTypeModel";
import { Prisma,CoverageType } from "@prisma/client";
import { CoverageTypeCreateDto, CoverageTypeUpdateDto } from "../dto/coverageType.dto";

export class CoverageTypeMapper {
  static fromCreateDtoToModel(dto: CoverageTypeCreateDto): CoverageTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: CoverageTypeUpdateDto): CoverageTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: CoverageTypeModel): Prisma.CoverageTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}