import { FlooringConditionModel } from "../../domain/models/FlooringConditionModel";
import { Prisma,FlooringCondition } from "@prisma/client";
import { FlooringConditionCreateDto, FlooringConditionUpdateDto } from "../dto/flooringCondition.dto";

export class FlooringConditionMapper {
  static fromCreateDtoToModel(dto: FlooringConditionCreateDto): FlooringConditionModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: FlooringConditionUpdateDto): FlooringConditionModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: FlooringConditionModel): Prisma.FlooringConditionCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}