import { LandingTypeModel } from "../../domain/models/LandingTypeModel";
import { Prisma,LandingType } from "@prisma/client";
import { LandingTypeCreateDto, LandingTypeUpdateDto } from "../dto/landingType.dto";

export class LandingTypeMapper {
  static fromCreateDtoToModel(dto: LandingTypeCreateDto): LandingTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: LandingTypeUpdateDto): LandingTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: LandingTypeModel): Prisma.LandingTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}