import { LightingSupportTypeModel } from "../../domain/models/LightingSupportTypeModel";
import { Prisma,LightingSupportType } from "@prisma/client";
import { LightingSupportTypeCreateDto, LightingSupportTypeUpdateDto } from "../dto/lightingSupportType.dto";

export class LightingSupportTypeMapper {
  static fromCreateDtoToModel(dto: LightingSupportTypeCreateDto): LightingSupportTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: LightingSupportTypeUpdateDto): LightingSupportTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: LightingSupportTypeModel): Prisma.LightingSupportTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}