import { PedestrianCrossingTypeModel } from "../../domain/models/PedestrianCrossingTypeModel";
import { Prisma,PedestrianCrossingType } from "@prisma/client";
import { PedestrianCrossingTypeCreateDto, PedestrianCrossingTypeUpdateDto } from "../dto/pedestrianCrossingType.dto";

export class PedestrianCrossingTypeMapper {
  static fromCreateDtoToModel(dto: PedestrianCrossingTypeCreateDto): PedestrianCrossingTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: PedestrianCrossingTypeUpdateDto): PedestrianCrossingTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: PedestrianCrossingTypeModel): Prisma.PedestrianCrossingTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}