import { PermissionModel } from "../../domain/models/PermissionModel";
import { Prisma,Permission } from "@prisma/client";
import { PermissionCreateDto, PermissionUpdateDto } from "../dto/permission.dto";

export class PermissionMapper {
  static fromCreateDtoToModel(dto: PermissionCreateDto): PermissionModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title: dto.title,
      roles: null,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: PermissionUpdateDto): PermissionModel {
    return {
      id: dto.id,
      title: dto.title,
      roles: null,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: PermissionModel): Prisma.PermissionCreateInput {
    return {
      title: model.title,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}