import { PositionModel } from "../../domain/models/PositionModel";
import { Prisma,Position } from "@prisma/client";
import { PositionCreateDto, PositionUpdateDto } from "../dto/position.dto";

export class PositionMapper {
  static fromCreateDtoToModel(dto: PositionCreateDto): PositionModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: PositionUpdateDto): PositionModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: PositionModel): Prisma.PositionCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}