import { RoadSignConditionModel } from "../../domain/models/RoadSignConditionModel";
import { Prisma,RoadSignCondition } from "@prisma/client";
import { RoadSignConditionCreateDto, RoadSignConditionUpdateDto } from "../dto/roadSignCondition.dto";

export class RoadSignConditionMapper {
  static fromCreateDtoToModel(dto: RoadSignConditionCreateDto): RoadSignConditionModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: RoadSignConditionUpdateDto): RoadSignConditionModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: RoadSignConditionModel): Prisma.RoadSignConditionCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}