import { RoadMarkingMaterialModel } from "../../domain/models/RoadMarkingMaterialModel";
import { Prisma,RoadMarkingMaterial } from "@prisma/client";
import { RoadMarkingMaterialCreateDto, RoadMarkingMaterialUpdateDto } from "../dto/roadMarkingMaterial.dto";

export class RoadMarkingMaterialMapper {
  static fromCreateDtoToModel(dto: RoadMarkingMaterialCreateDto): RoadMarkingMaterialModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: RoadMarkingMaterialUpdateDto): RoadMarkingMaterialModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: RoadMarkingMaterialModel): Prisma.RoadMarkingMaterialCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}