import { RoadSignMaterialModel } from "../../domain/models/RoadSignMaterialModel";
import { Prisma,RoadSignMaterial } from "@prisma/client";
import { RoadSignMaterialCreateDto, RoadSignMaterialUpdateDto } from "../dto/roadSignMaterial.dto";

export class RoadSignMaterialMapper {
  static fromCreateDtoToModel(dto: RoadSignMaterialCreateDto): RoadSignMaterialModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: RoadSignMaterialUpdateDto): RoadSignMaterialModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: RoadSignMaterialModel): Prisma.RoadSignMaterialCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}