import { RoleModel } from "../../domain/models/RoleModel";
import { Prisma,Role } from "@prisma/client";
import { RoleCreateDto, RoleUpdateDto } from "../dto/role.dto";

export class RoleMapper {
  static fromCreateDtoToModel(dto: RoleCreateDto): RoleModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title: dto.title,
      permissions: null,
      users: null,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: RoleUpdateDto): RoleModel {
    return {
      id: dto.id,
      title: dto.title,
      permissions: null,
      users: null,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: RoleModel): Prisma.RoleCreateInput {
    return {
      title: model.title,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}