import { SideStoneStampModel } from "../../domain/models/SideStoneStampModel";
import { Prisma,SideStoneStamp } from "@prisma/client";
import { SideStoneStampCreateDto, SideStoneStampUpdateDto } from "../dto/sideStoneStamp.dto";

export class SideStoneStampMapper {
  static fromCreateDtoToModel(dto: SideStoneStampCreateDto): SideStoneStampModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: SideStoneStampUpdateDto): SideStoneStampModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: SideStoneStampModel): Prisma.SideStoneStampCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}