import { SideModel } from "../../domain/models/SideModel";
import { Prisma,Side } from "@prisma/client";
import { SideCreateDto, SideUpdateDto } from "../dto/side.dto";

export class SideMapper {
  static fromCreateDtoToModel(dto: SideCreateDto): SideModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: SideUpdateDto): SideModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: SideModel): Prisma.SideCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}