import { SideStoneTypeModel } from "../../domain/models/SideStoneTypeModel";
import { Prisma,SideStoneType } from "@prisma/client";
import { SideStoneTypeCreateDto, SideStoneTypeUpdateDto } from "../dto/sideStoneType.dto";

export class SideStoneTypeMapper {
  static fromCreateDtoToModel(dto: SideStoneTypeCreateDto): SideStoneTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: SideStoneTypeUpdateDto): SideStoneTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: SideStoneTypeModel): Prisma.SideStoneTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}