import { WellsTypeModel } from "../../domain/models/WellsTypeModel";
import { Prisma,WellsType } from "@prisma/client";
import { WellsTypeCreateDto, WellsTypeUpdateDto } from "../dto/wellsType.dto";

export class WellsTypeMapper {
  static fromCreateDtoToModel(dto: WellsTypeCreateDto): WellsTypeModel {
    return {
      id: 0, // ID will be auto-generated by the database
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }

  static fromUpdateDtoToModel(dto: WellsTypeUpdateDto): WellsTypeModel {
    return {
      id: dto.id,
      title_ru: dto.title_ru,
      title_kk: dto.title_kk,
      title_en: dto.title_en,
      created_at: new Date(),
      updated_at: new Date(),
    };
  }


  static toPersistence(model: WellsTypeModel): Prisma.WellsTypeCreateInput {
    return {
      title_ru: model.title_ru,
      title_kk: model.title_kk,
      title_en: model.title_en,
      created_at: model.created_at,
      updated_at: model.updated_at,
    };
  }
}